name: MariusAdminPlugin
version: 1.0.0
main: dev.marius.map.spigot.MAPlugin

api-version: 1.21.1
authors: [ Marius ]
description: Marius Admin Plugin
website: https://github.com/avolgha

permissions:
  map.*:
    default: op
    children:
      - map.staffchat.*
      - map.tpto.*
      - map.bypass.*